export interface CurriculumGameMeta {
  id: string;
  name: string;
  emoji: string;
  domain: '운동' | '스포츠' | '표현' | '안전';
  code: string;
  target: string;
  duration: number;
}

export const CURRICULUM_GAMES_META: Record<string, CurriculumGameMeta> = {
  // [1] 운동 영역 (10종)
  'breath-pacer-478': {
    id: 'breath-pacer-478',
    name: '4-7-8 자율신경 이완 페이서',
    emoji: '🌬️',
    domain: '운동',
    code: '[4체01-04]',
    target: '호흡 폐활량 및 자율신경 이완',
    duration: 25,
  },
  'peripheral-vision-360': {
    id: 'peripheral-vision-360',
    name: '360° 주변시야 동체인식',
    emoji: '👁️',
    domain: '운동',
    code: '[6체01-02]',
    target: '주변시야 및 신경 협응력',
    duration: 20,
  },
  'shuttle-run-beep': {
    id: 'shuttle-run-beep',
    name: '셔틀런 삑 비트 인터벌',
    emoji: '🏃',
    domain: '운동',
    code: '[6체01-01]',
    target: '심폐지구력 및 페이스 조절',
    duration: 25,
  },
  'mobility-joint-circle': {
    id: 'mobility-joint-circle',
    name: '관절 가동성 스무스 서클',
    emoji: '🧘',
    domain: '운동',
    code: '[4체01-03]',
    target: '발목·손목 관절 가동성',
    duration: 20,
  },
  'foot-center-balance': {
    id: 'foot-center-balance',
    name: '족저압 무게중심 센서',
    emoji: '⚖️',
    domain: '운동',
    code: '[6체01-02]',
    target: '고유수용성 평형 감각',
    duration: 20,
  },
  'agility-dot-drill': {
    id: 'agility-dot-drill',
    name: '5점 닷 드릴 풋워크 시퀀서',
    emoji: '⚡',
    domain: '운동',
    code: '[4체01-02]',
    target: '신속 민첩성 풋워크',
    duration: 20,
  },
  'eccentric-isom-push': {
    id: 'eccentric-isom-push',
    name: '등척성 파워 게이지 홀드',
    emoji: '💪',
    domain: '운동',
    code: '[6체01-05]',
    target: '근신경 조절 및 근지구력',
    duration: 20,
  },
  'posture-spine-align': {
    id: 'posture-spine-align',
    name: '척추 중립 정렬 축 얼라인',
    emoji: '🧗',
    domain: '운동',
    code: '[4체01-04]',
    target: '바른 자세 및 척추 건강',
    duration: 20,
  },
  'pulse-zone-target': {
    id: 'pulse-zone-target',
    name: '목표 심박수 트레이닝 존',
    emoji: '💓',
    domain: '운동',
    code: '[6체01-01]',
    target: '심박 반응 인지 및 유산소 존',
    duration: 20,
  },
  'cross-lateral-brain': {
    id: 'cross-lateral-brain',
    name: '좌우 교차 크로스 브레인짐',
    emoji: '🧩',
    domain: '운동',
    code: '[4체01-02]',
    target: '양뇌 교차 신경계 협응',
    duration: 20,
  },

  // [2] 스포츠 영역 (10종)
  'wind-archery-pro': {
    id: 'wind-archery-pro',
    name: '풍향·풍속 탄도 윈드 양궁',
    emoji: '🏹',
    domain: '스포츠',
    code: '[6체02-04]',
    target: '환경 오프셋 탄도 조준',
    duration: 25,
  },
  'volleyball-apex-set': {
    id: 'volleyball-apex-set',
    name: '배구 정점 포물선 토스·스파이크',
    emoji: '🏐',
    domain: '스포츠',
    code: '[4체02-06]',
    target: '포물선 꼭짓점 궤적 타이밍',
    duration: 20,
  },
  'strike-zone-vision': {
    id: 'strike-zone-vision',
    name: '140km/h 스트라이크존 선구안',
    emoji: '⚾',
    domain: '스포츠',
    code: '[6체02-06]',
    target: '동체시력 및 볼 판정 선구안',
    duration: 20,
  },
  'offside-breaker-pass': {
    id: 'offside-breaker-pass',
    name: '3:2 오프사이드 트랩 브레이커',
    emoji: '⚽',
    domain: '스포츠',
    code: '[6체02-05]',
    target: '수비 라인 돌파 스루패스',
    duration: 20,
  },
  'badminton-drop-clear': {
    id: 'badminton-drop-clear',
    name: '셔틀콕 드롭 vs 클리어 선택',
    emoji: '🏸',
    domain: '스포츠',
    code: '[4체02-06]',
    target: '코트 빈 공간 공략 전술',
    duration: 20,
  },
  'basketball-free-throw': {
    id: 'basketball-free-throw',
    name: '포물선 각도·파워 자유투',
    emoji: '🏀',
    domain: '스포츠',
    code: '[6체02-05]',
    target: '투사체 궤적 힘·각도 조절',
    duration: 25,
  },
  'curling-weight-control': {
    id: 'curling-weight-control',
    name: '컬링 하우스 힘 조절 스톤',
    emoji: '🥌',
    domain: '스포츠',
    code: '[4체02-05]',
    target: '마찰력 계산 표적 안착',
    duration: 25,
  },
  'taekwondo-counter-kick': {
    id: 'taekwondo-counter-kick',
    name: '태권도 반격 발차기 패링',
    emoji: '🥋',
    domain: '스포츠',
    code: '[6체02-02]',
    target: '공격 타이밍 회피 반격',
    duration: 20,
  },
  'tabletennis-spin-read': {
    id: 'tabletennis-spin-read',
    name: '탁구 커트/탑스핀 회전 판독',
    emoji: '🏓',
    domain: '스포츠',
    code: '[4체02-06]',
    target: '공 회전 방향 예측 리시브',
    duration: 20,
  },
  'baseball-bunt-defense': {
    id: 'baseball-bunt-defense',
    name: '번트 타구 대시 & 1루 송구',
    emoji: '⚾',
    domain: '스포츠',
    code: '[6체02-06]',
    target: '수비 대시 및 송구 정확도',
    duration: 20,
  },

  // [3] 표현 및 안전 영역 (10종)
  'cpr-compression-110': {
    id: 'cpr-compression-110',
    name: '골든타임 CPR 100~120 BPM 압박',
    emoji: '🚨',
    domain: '안전',
    code: '[6체05-02]',
    target: '심폐소생술 표준 템포 압박',
    duration: 25,
  },
  'aed-defibrillator-pad': {
    id: 'aed-defibrillator-pad',
    name: '자동심장충격기 AED 패드 부착',
    emoji: '⚡',
    domain: '안전',
    code: '[6체05-02]',
    target: 'AED 사용 순서 및 감전 안전',
    duration: 20,
  },
  'water-rescue-throw': {
    id: 'water-rescue-throw',
    name: '물놀이 안전 익수자 구명환 투척',
    emoji: '🛟',
    domain: '안전',
    code: '[4체05-03]',
    target: '유속 계산 구명 도구 투척',
    duration: 20,
  },
  'heatwave-pm25-shield': {
    id: 'heatwave-pm25-shield',
    name: '폭염·미세먼지 체육 안전 디시전',
    emoji: '☀️',
    domain: '안전',
    code: '[4체05-01]',
    target: '기상 경보별 안전 수칙 선택',
    duration: 20,
  },
  'rice-treatment-firstaid': {
    id: 'rice-treatment-firstaid',
    name: '발목 염좌 RICE 4단계 응급처치',
    emoji: '🩹',
    domain: '안전',
    code: '[6체05-01]',
    target: '염좌 RICE 응급처치 순서',
    duration: 20,
  },
  'step-mania-4lane': {
    id: 'step-mania-4lane',
    name: '4레인 댄스 스텝 콤보 시퀀서',
    emoji: '🕺',
    domain: '표현',
    code: '[4체03-05]',
    target: '리듬 비트 스텝 콤보',
    duration: 25,
  },
  'shadow-pose-sculpture': {
    id: 'shadow-pose-sculpture',
    name: '신체 실루엣 섀도우 조형 매칭',
    emoji: '👥',
    domain: '표현',
    code: '[6체03-02]',
    target: '신체 조형성 및 정지선 표현',
    duration: 20,
  },
  'ribbon-wave-stream': {
    id: 'ribbon-wave-stream',
    name: '리듬체조 리본 나선형 궤적',
    emoji: '🌊',
    domain: '표현',
    code: '[4체03-06]',
    target: '도구 움직임 궤적 연속성',
    duration: 20,
  },
  'emotion-freeze-mime': {
    id: 'emotion-freeze-mime',
    name: '희로애락 감정 마임 정지 포즈',
    emoji: '🎭',
    domain: '표현',
    code: '[4체03-04]',
    target: '감정 신체 극대화 표현',
    duration: 20,
  },
  'partner-mirror-duet': {
    id: 'partner-mirror-duet',
    name: '거울 짝 듀엣 무용 타이밍 매칭',
    emoji: '🪞',
    domain: '표현',
    code: '[6체03-05]',
    target: '파트너 관계 중심 협력 무용',
    duration: 20,
  },
};
